### PR TITLE
Simple cleanups

### PR DESCRIPTION
**Pull request by miscco**
These are some simple cleanups that I thought applicable when skimming the code.

I dont really know about the custom versions of asinh acosh etc as they are part of the standart c++ cmath library.

### CODE REVIEW

**Comment by martinrotter** [comment]
Looks fine to me.

**Comment by miscco** [comment]
I dont know if it is important but i use tab only in qt so it made the 4 spaces into one tab. Should i change that?

**Comment by martinrotter** [comment]
Oh yes, follow same code style/setup as the rest of this project.

**Comment by miscco** [comment]
I cleaned up the wrong whitespace.

**Comment by beltoforion** [comment]
From the diff it looks fine to me too. I'll pull this blindly. Hoping the repository doesn't explode.

**Pull request merged**
