### PR TITLE
CMake build file for muparserx project

### PR DESCRIPTION
**Pull request by guruofquality**
Referencing https://github.com/beltoforion/muparserx/issues/49 A CMake build system could replace several other build systems and aid in packaging. Ive tested this on ubuntu w/ gcc and windows with msvc.

### CODE REVIEW

**Comment by TimothyGu** [comment]
+1. For a library like muparserx with no dependencies, CMake is perfect.

**Comment by martinrotter** [comment]
For me, it looks overally very good.

**Comment by martinrotter** [comment]
@beltoforion Do you have any thoughts on this? I believe it could/should be merged now. :)

**Comment by beltoforion** [comment]
Sorry, I can not introduce any build system that does allow the creation of a shared library for a project that is using STL in its API. Its an inherently bad idea to do this.

**Comment by guruofquality** [comment]
I know the pain of C++ ABI compatibility. Per @rashadkm comments, I changed the project to build a static library by default. The user would have to explicitly pass -DBUILD_SHARED_LIBS=ON to cmake to build a shared library instead. However, I could add a warning or even error if the user ever tried to set BUILD_SHARED_LIBS=ON Would that help?

**Comment by beltoforion** [comment]
First thanks for setting up the cmake file. I appreciate your support..

**Short answer:** If someone really wants to shoot himself in the foot by using a shared library i would accept a solution that provides a strong warning and makes it clear that I do not recommend  the use of a shared library and thus cannot provide support for any issues related to the use of a shared library of muparserx. 

**More Detailed Answer:** If there is a BUILD_SHARED_OPTION people will use it and they expect it to work. But it can't really work. The only thing you would do is build a shared library for a specific OS version using a specific STL version. You can't safely take the library to another distribution or even the same distribution having another patchlevel. Sure it will work in 95% of the cases but sometimes It might break existing applications and people will come here to complain. They won't understand the problem and will ask me to fix it. My time is limited and even explaining this over and over again is tiresome. I'm unwilling to provide support for a shared library of muparserx and strongly advise against using muparserx as a shared library. I don't want it to appear in precompiled form in any linux distribution for the same reason and I will not care about checking the ABI for every minor release. I might knowingly or unknowingly break the ABI of muparserx even in minor version changes.

**Comment by bugbrains** [comment]
Short question:
why this couldn't be merged.?

Comments:
you can make it clear to not use BUILD_SHARED_LIBS=OFF and can be the case by default for muparserx. Then if user tries to build shared, then he is own his own. You don't want to care or reply for it. But having an cmake option to build shared which is OFF and turning on gives warning makes it clear.

But what I cannot understand is why the cmake or a flexible build shouldn't be supported?. for disableing shared build.? If you cannot provide future support then no worries. The same worry for if I want to build shared library now. I build muparserx which works 95%

**Comment by aaronpburke** [comment]
Instead of throwing a big, scary warning if BUILD_SHARED_LIBS is enabled, you can bypass that entirely by specifying the STATIC keyword in the add_library command. It forces the resulting library to be a static library 100% of the time, regardless of user settings.

e.g.,
add_library(muparserx ${MUPARSERX_SOURCES})
becomes
add_library(muparserx STATIC ${MUPARSERX_SOURCES})

**Comment by bugbrains** [comment]
@aaronpburke, then shared libs is never possible without modifying cmakelists.txt. This is what @beltoforion insist on having in muparserx. Anyway if that is acceptable, atleast this make build process easier rather than going for qt-qmake.  For anyone insist on having muparserx shared must use a modified cmake. I will never understand how disable shared lib in build scripts make it work. As I said before, I have a shared build of muparserx for various compiler and platforms even though the developer disabled it.

**Comment by beltoforion** [comment]
I merged the branch. I didn't do any test yet. However i will likely disable shared builds or at least add a warning that i will not support any problems arising from shared builds.

**Pull request merged**
