### PR TITLE
Added basic flow control features

### PR DESCRIPTION
**Pull request by UnsureJedi**
Added several flow control statements:
1. Loop {} - works similar to C While (1) {}.
2. If {} Else {} - C-style If-Then-Else. Works exactly the same but there are a couple of differences in it's typing. Refer to Example.cpp.
3. Break statement - must be present in every Loop{} statement. Works just like C counterpart.

In Example.cpp I've changed the calc() to accept a keyword "test". Type it in command line when Example is run and it will execute the block of code (currently lines 892-915). All of the above features are used there.

Aside from these, added a {;"string"} construct, albeit sloppy in its implementation (mostly just copy-paste of existing code). It's purpose is to provide a more convenient way to nest strings so one doesn't have to use numerous literal quotes with backslashes.

Also added some functions in mpParserBase to control parser constants and variables:
1. SetConst()
2. GetConst()
3. SetVar()
4. GetVar()

Added AssignVars() which copies variables and constants from another ParserX object.
These functions can be used with user defined functions to access parser constants and variables. I used them at first to simulate loops and conditionals, but it proved way too slow.

Finally, my VS2017 has rearranged code, adding and removing spaces, which interferes with comparison, so the actual number of changes is a lot smaller than Git shows. If needed I can try to revert those changes to clean differences a bit.

### CODE REVIEW

**Comment by beltoforion** [comment]
I'm impressed you managed to implement something like this and it might actually be useful provided it works properly. However i do not see a chance to pull this modification as it is since it contains a lot of constructs that i consider harmful

- Use of hardcoded array lengths
- override keywords removed
- custom replacement for standard library functions (log2, asinh, acosh, atanh)
- removal of virtual destructors (i.e. ~IPrecedence)

**Comment by UnsureJedi** [comment]
Hello! Nice to see it can be useful. Down to business:
- About hardcoded lengths: yes I knew they could be a problem, so I planned to replace them eventually with runtime allocation. Since you consider it an immediate problem I will do the replacements soon.
- About override keywords, standard functions and virtual destructors: weird thing is, that's probably VS's autocorrection that removed virtual destructors and override keywords and I don't remember replacing math functions either. At the time I didn't really knew the code yet (took me a couple of months to get acquainted) so I just let the VS do its thing. 

I'll try to revert those harmful changes and then I'll update the fork and pull request. Thankfully, comparing of your master branch and the fork should make it easier and faster.
Any further directions will be greatly appreciated.

**Comment by UnsureJedi** [comment]
Ok, done. Bad changes have been undone and arrays are allocated at runtime. Also cleaned up trash differences, so the code is easier to compare now.

**Comment by UnsureJedi** [comment]
Look, @beltoforion, if this pull request is unacceptable - I understand, but you could close it yourself and there would be no suspense. I have 14 more commits stockpiled that I didn't push because I waited for your decision. For now, if you consider it good enough to be merged, write here, I'll then create a separate fork and pull request.

**Comment by beltoforion** [comment]
I'm sorry. I'm unable to invest the time needed push this forward. This is the case for years now and unfortunately muparserx is no longer high on my list of priorities. I'm willing to keep it running but truth be told i'm lacking the commitment to introduce a major change like this without proper review. I should have communicated this clearly but in the beginning I felt that maybe i could make it work. I can't.

**Pull request closed without merging**
